version: "3.8"

networks:
  php-app:
    driver: bridge
volumes:
  db_volume:
    driver: local

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - "./app:/var/www/html"
    ports:
      - "8085:80"
    networks:
      php-app:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: pguser
    ports:
      - "5433:5433"
    volumes:
      - "db_volume:/var/lib/postgresql/data"
    command: -p 5433
    networks:
      - php-app
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - php-app