version: "3.8"

networks:
  php-app:
    driver: bridge
volumes:
  db_volume:
    driver: local

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - "./app:/var/www/html"
      - "./tmp:/tmp/php"
    ports:
      - "8085:80"
    networks:
      php-app:
  db:
    image: mysql:8.0.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - "./db_volume:/var/lib/mysql"
      - "./docker/mysql/init.sql:/data/application/init.sql"
    networks:
      - php-app
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - "9000:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - php-app